# The Dot Product

*Course notes for **Math for Machine Learning**, C1 · W3 · L1 · V06 — "The Dot Product" (DeepLearning.AI).*

The **dot product** is one of the most important operations in linear algebra — a compact way to combine two vectors into a single number, and the building block for expressing systems of linear equations with matrices and vectors. This lecture covers:

- The dot product from a concrete **cost** example.
- Its formal **definition** (row vector $\times$ column vector).
- The link between the **dot product and the $L_2$ norm**.
- The **transpose** operation on vectors and matrices.

In [1]:
import numpy as np

np.set_printoptions(precision=3, suppress=True)

## 1. Motivation: the cost of a basket of fruit

Suppose you buy **2 apples, 4 bananas, 1 cherry**, priced at **\$3, \$5, \$2** each. How much does everything cost?

Encode the quantities and the prices as vectors:

$$ \text{quantities} = \begin{pmatrix} 2 \\ 4 \\ 1 \end{pmatrix}, \qquad \text{prices} = \begin{pmatrix} 3 \\ 5 \\ 2 \end{pmatrix}. $$

Multiply each quantity by its price and add:

$$ 2\cdot 3 + 4\cdot 5 + 1\cdot 2 = 6 + 20 + 2 = 28. $$

That sum-of-products **is exactly the dot product**.

In [2]:
quantities = np.array([2, 4, 1])
prices     = np.array([3, 5, 2])

# element-wise cost per fruit, then the total
print('cost per fruit =', quantities * prices)      # [6, 20, 2]
print('total cost     =', np.dot(quantities, prices))  # 28

cost per fruit = [ 6 20  2]
total cost     = 28


## 2. Definition of the dot product

For two vectors with the **same number of components** $x = (x_1, \dots, x_n)$ and $y = (y_1, \dots, y_n)$:

$$ x \cdot y \;=\; \langle x, y \rangle \;=\; x_1 y_1 + x_2 y_2 + \dots + x_n y_n \;=\; \sum_{i=1}^{n} x_i\, y_i. $$

It takes two vectors and returns a **single number**. Conventionally the first vector is written as a **row** and the second as a **column**. The angle-bracket form $\langle x, y \rangle$ is another common notation.

In [3]:
x = np.array([2, 4, 1])
y = np.array([3, 5, 2])

print('np.dot(x, y) =', np.dot(x, y))
print('x @ y        =', x @ y)              # @ is the matmul / dot operator
print('by hand      =', sum(xi*yi for xi, yi in zip(x, y)))

np.dot(x, y) = 28
x @ y        = 28
by hand      = 28


## 3. Connection between the dot product and the norm

Take $v = (4, 3)$, whose $L_2$ norm is $5$. Notice that

$$ 4^2 + 3^2 = 4\cdot 4 + 3\cdot 3 = v \cdot v = 25. $$

This is always true — the **$L_2$ norm is the square root of the dot product of a vector with itself**:

$$ \|v\|_2 = \sqrt{v \cdot v} = \sqrt{\langle v, v \rangle}. $$

In [4]:
v = np.array([4, 3])
print('v . v           =', v @ v)                 # 25
print('sqrt(v . v)     =', np.sqrt(v @ v))         # 5.0
print('np.linalg.norm  =', np.linalg.norm(v))      # 5.0  (matches)

v . v           = 25
sqrt(v . v)     = 5.0
np.linalg.norm  = 5.0


## 4. The transpose

Turning a **column vector into a row vector** (and vice versa) is the **transpose**, written with a superscript $T$:

$$ \begin{pmatrix} 4 \\ 3 \end{pmatrix}^{\!T} = \begin{pmatrix} 4 & 3 \end{pmatrix}. $$

The transpose also applies to **matrices**: it turns each **column into a row**, so the **dimensions swap** — a $3 \times 2$ matrix becomes a $2 \times 3$ matrix.

$$ \begin{pmatrix} 1 & 4 \\ 2 & 5 \\ 3 & 6 \end{pmatrix}^{\!T} = \begin{pmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \end{pmatrix}. $$

In [5]:
# transpose of a matrix: columns become rows, dimensions swap
M = np.array([[1, 4],
              [2, 5],
              [3, 6]])
print('M  shape', M.shape)
print(M)
print()
print('M.T  shape', M.T.shape)
print(M.T)

M  shape (3, 2)
[[1 4]
 [2 5]
 [3 6]]

M.T  shape (2, 3)
[[1 2 3]
 [4 5 6]]


## 5. Dot product as (row) $\times$ (column)

In many contexts the dot product is expected to have a **row vector on the left** and a **column vector on the right**. Writing $x$ and $y$ as column vectors, the dot product is $x^T y$:

$$ x^{T} y = \begin{pmatrix} x_1 & \cdots & x_n \end{pmatrix} \begin{pmatrix} y_1 \\ \vdots \\ y_n \end{pmatrix} = \sum_{i=1}^{n} x_i\, y_i. $$

This is why you often see a **transpose** used on one vector — to line the shapes up as (row)$\times$(column).

In [6]:
# x^T y using explicit column vectors (shape n x 1)
xc = np.array([[2], [4], [1]])   # 3 x 1 column
yc = np.array([[3], [5], [2]])   # 3 x 1 column

result = xc.T @ yc               # (1 x 3) @ (3 x 1) -> 1 x 1
print('x^T y =', result, ' shape', result.shape)
print('scalar value =', result.item())

x^T y = [[28]]  shape (1, 1)
scalar value = 28


## Summary

- The **dot product** $x \cdot y = \sum_i x_i y_i$ combines two same-length vectors into a single number (e.g. quantities $\cdot$ prices $=$ total cost).
- Notations: $x \cdot y$, $\langle x, y \rangle$, and $x^T y$ (row $\times$ column) all mean the same thing.
- **Norm link:** $\|v\|_2 = \sqrt{v \cdot v}$ — the $L_2$ norm is the square root of a vector dotted with itself.
- The **transpose** ($\cdot^T$) turns columns into rows; on a matrix it swaps the dimensions ($m \times n \to n \times m$).
- In NumPy: `np.dot(x, y)` or `x @ y`; matrix transpose is `M.T`.