# Row Operations That Preserve Singularity

*Course notes for **Math for Machine Learning**, C1 · W2 · L1 — "Row Operations That Preserve Singularity" (DeepLearning.AI).*

Elimination manipulates a matrix with **row operations**. For that to be a valid way to study a system, those operations must not change *whether the matrix is singular*. They don't — and we can see exactly what each one does to the **determinant**.

Throughout we use $\begin{bmatrix}5&1\\4&3\end{bmatrix}$, whose determinant is $5\cdot 3 - 1\cdot 4 = 11$ (non-singular).

| Row operation | Effect on $\det$ | Singularity |
|---------------|------------------|-------------|
| Switch two rows | sign flips ($\det \to -\det$) | preserved |
| Multiply a row by $k \neq 0$ | scales ($\det \to k\,\det$) | preserved |
| Add one row to another | unchanged | preserved |

In [1]:
import numpy as np

A = np.array([[5.0, 1.0], [4.0, 3.0]])
det = lambda M: round(float(np.linalg.det(M)))
print("A =\n", A.astype(int))
print("det(A) =", det(A), "-> non-singular")

A =
 [[5 1]
 [4 3]]
det(A) = 11 -> non-singular


## 1. Switching rows — the sign flips

$$ \begin{bmatrix}5&1\\4&3\end{bmatrix}\;(\det = 11) \;\longrightarrow\; \begin{bmatrix}4&3\\5&1\end{bmatrix}\;(\det = 4\cdot 1 - 3\cdot 5 = -11). $$

Swapping two rows **negates** the determinant. The magnitude is the same, so a zero determinant stays zero — **singularity is preserved**.

In [2]:
swapped = A[[1, 0], :]
print("swapped =\n", swapped.astype(int))
print(f"det: {det(A)}  ->  {det(swapped)}   (sign flipped, |det| unchanged)")

swapped =
 [[4 3]
 [5 1]]
det: 11  ->  -11   (sign flipped, |det| unchanged)


## 2. Multiplying a row by a non-zero scalar — det scales by $k$

Multiply row 1 by $10$:

$$ \begin{bmatrix}5&1\\4&3\end{bmatrix} \;\longrightarrow\; \begin{bmatrix}50&10\\4&3\end{bmatrix}, \qquad \det = 5\cdot(10\cdot 3) - 1\cdot(10\cdot 4) = 10 \cdot 11 = 110. $$

Scaling a row by $k$ multiplies the determinant by $k$. As long as $k \neq 0$, a non-zero determinant stays non-zero (and zero stays zero) — **singularity is preserved**.

In [3]:
k = 10
scaled = A.copy(); scaled[0] = k * scaled[0]
print("scaled =\n", scaled.astype(int))
print(f"det: {det(A)}  ->  {det(scaled)}   (= {k} x {det(A)})")

scaled =
 [[50 10]
 [ 4  3]]
det: 11  ->  110   (= 10 x 11)


## 3. Adding one row to another — det unchanged

Replace row 1 with row 1 + row 2:

$$ \begin{bmatrix}5&1\\4&3\end{bmatrix} \;\longrightarrow\; \begin{bmatrix}9&4\\4&3\end{bmatrix}, \qquad \det = 9\cdot 3 - 4\cdot 4 = 27 - 16 = 11. $$

Adding a (multiple of a) row to another row leaves the determinant **exactly unchanged**. This is the workhorse operation of elimination — and the reason elimination never alters singularity.

In [4]:
added = A.copy(); added[0] = added[0] + added[1]
print("added =\n", added.astype(int))
print(f"det: {det(A)}  ->  {det(added)}   (unchanged)")

added =
 [[9 4]
 [4 3]]
det: 11  ->  11   (unchanged)


## 4. Why "preserves singularity" is the point

None of these operations can turn a zero determinant into a non-zero one or vice versa:

- swap: $\det \to -\det$ — zero ⇔ zero,
- scale by $k\neq 0$: $\det \to k\det$ — zero ⇔ zero,
- add a row: $\det \to \det$ — unchanged.

So a **singular matrix stays singular** and a **non-singular matrix stays non-singular** under every step of elimination. The check below confirms it on a singular matrix too.

In [5]:
S = np.array([[1.0, 1.0], [2.0, 2.0]])   # singular, det = 0
ops = {
    "original":       S,
    "swapped":        S[[1, 0], :],
    "row0 x 10":      np.array([10 * S[0], S[1]]),
    "row0 += row1":   np.array([S[0] + S[1], S[1]]),
}
for name, M in ops.items():
    print(f"{name:14s} det = {det(M):3d}  ->  still singular")

original       det =   0  ->  still singular
swapped        det =   0  ->  still singular
row0 x 10      det =   0  ->  still singular
row0 += row1   det =   0  ->  still singular


## 5. Takeaways

- The three elementary **row operations** change the determinant in predictable ways but never change whether it is **zero**.
  - **Switch rows:** determinant sign flips.
  - **Scale a row by $k\neq 0$:** determinant multiplies by $k$.
  - **Add a row to another:** determinant unchanged.
- Therefore every row operation **preserves singularity** — singular stays singular, non-singular stays non-singular.
- This is what makes **elimination** (and the REF/RREF reductions) legitimate: reducing a matrix never changes its singular/non-singular status.

*Companion:* [systems to matrices / row echelon form](./C1_W2_L1_systems_to_matrices.ipynb) · [the determinant](./C1_W1_L1_the_determinant.ipynb).