# SVD from Eigen-Decomposition
This notebook computes U, Σ, V from AAᵀ and AᵀA and compares with NumPy SVD.

In [9]:
import numpy as np

## Define matrix A

In [10]:
A = np.array([[3,0],[-1,2]], float)
A

array([[ 3.,  0.],
       [-1.,  2.]])

## Compute AAᵀ and AᵀA

In [11]:
AAT = A @ A.T
ATA = A.T @ A
AAT, ATA

(array([[ 9., -3.],
        [-3.,  5.]]),
 array([[10., -2.],
        [-2.,  4.]]))

## Eigen-decomposition

In [12]:
eigvals_U, eigvecs_U = np.linalg.eig(AAT)
eigvals_V, eigvecs_V = np.linalg.eig(ATA)
eigvals_U, eigvecs_U, eigvals_V, eigvecs_V

(array([10.60555128,  3.39444872]),
 array([[ 0.8816746 ,  0.47185793],
        [-0.47185793,  0.8816746 ]]),
 array([10.60555128,  3.39444872]),
 array([[ 0.95709203,  0.28978415],
        [-0.28978415,  0.95709203]]))

## Sort and normalize eigenvectors

In [13]:

idx_U = np.argsort(-eigvals_U)
idx_V = np.argsort(-eigvals_V)

eigvals_U = eigvals_U[idx_U]
eigvals_V = eigvals_V[idx_V]

U = eigvecs_U[:, idx_U]
V = eigvecs_V[:, idx_V]

U = U / np.linalg.norm(U, axis=0)
V = V / np.linalg.norm(V, axis=0)

singular_vals = np.sqrt(eigvals_U)
m,n=A.shape
Sigma = np.zeros((m,n))
np.fill_diagonal(Sigma, singular_vals)

U, Sigma, V


(array([[ 0.8816746 ,  0.47185793],
        [-0.47185793,  0.8816746 ]]),
 array([[3.25661654, 0.        ],
        [0.        , 1.84240298]]),
 array([[ 0.95709203,  0.28978415],
        [-0.28978415,  0.95709203]]))

In [16]:
U @ Sigma @ V.T

array([[ 3.00000000e+00,  2.17754167e-16],
       [-1.00000000e+00,  2.00000000e+00]])

## Align signs with NumPy SVD

In [15]:

U_svd, S_svd, Vt_svd = np.linalg.svd(A)

for i in range(len(S_svd)):
    if np.sign(U[:, i][0]) != np.sign(U_svd[:, i][0]):
        U[:, i] *= -1
    if np.sign(V[:, i][0]) != np.sign(Vt_svd.T[:, i][0]):
        V[:, i] *= -1

U, Sigma, V.T


(array([[-0.8816746 ,  0.47185793],
        [ 0.47185793,  0.8816746 ]]),
 array([[3.25661654, 0.        ],
        [0.        , 1.84240298]]),
 array([[-0.95709203,  0.28978415],
        [ 0.28978415,  0.95709203]]))