In [8]:
import math

import numpy as np

In [ ]:
A = np.array([[0, 2], [1, 1], [-2, 0]], dtype=float)

In [4]:
A.T @ A

array([[5., 1.],
       [1., 5.]])

In [5]:
np.linalg.eigvals(A.T @ A)

array([6., 4.])

In [11]:
Sigma = np.array([[math.sqrt(6), 0], [0, 2]])
Sigma

array([[2.44948974, 0.        ],
       [0.        , 2.        ]])

In [ ]:
np.linalg.eie

In [3]:
U, s, V = np.linalg.svd(A)

In [12]:
U

array([[-5.77350269e-01,  7.07106781e-01, -4.08248290e-01],
       [-5.77350269e-01, -1.43931301e-16,  8.16496581e-01],
       [ 5.77350269e-01,  7.07106781e-01,  4.08248290e-01]])

In [13]:
s

array([2.44948974, 2.        ])

In [14]:
V

array([[-0.70710678, -0.70710678],
       [-0.70710678,  0.70710678]])

In [15]:
2.44948974 ** 2

5.999999986365268