
# Matrix Decompositions

This notebook introduces **matrix decompositions**, which express a matrix as a product of simpler, structured matrices.

Matrix decompositions are central to numerical linear algebra, optimization, scientific computing, and machine learning. They transform abstract spectral ideas into **computational tools**.



## Mathematical Preliminaries

We assume familiarity with:

- Matrix multiplication
- Invertible matrices
- Rank and linear independence
- Eigenvalues (from Spectral Theory)

All matrices are real unless stated otherwise.



## Why Decompositions Matter

Matrix decompositions allow us to:

- Solve linear systems efficiently
- Understand matrix structure
- Improve numerical stability
- Reduce high-dimensional data

Core idea:
> Complicated matrices become manageable when factored into simple components.



## LU Decomposition

For a square matrix $A$, LU decomposition factors

$$
A = LU
$$

where:
- $L$ is lower triangular (unit diagonal)
- $U$ is upper triangular

Used for:
- Fast solution of $Ax = b$
- Repeated solves with different right-hand sides

LU may require **row pivoting** for numerical stability.


In [1]:

import numpy as np
from scipy.linalg import lu

A = np.array([[2., 3., 1.],
              [4., 7., 7.],
              [-2., 4., 5.]])

P, L, U = lu(A)
P, L, U


(array([[0., 0., 1.],
        [1., 0., 0.],
        [0., 1., 0.]]),
 array([[ 1.        ,  0.        ,  0.        ],
        [-0.5       ,  1.        ,  0.        ],
        [ 0.5       , -0.06666667,  1.        ]]),
 array([[ 4.        ,  7.        ,  7.        ],
        [ 0.        ,  7.5       ,  8.5       ],
        [ 0.        ,  0.        , -1.93333333]]))


## QR Decomposition

Any matrix $A \in \mathbb{R}^{m \times n}$ can be written as

$$
A = QR
$$

where:
- $Q$ has orthonormal columns
- $R$ is upper triangular

QR arises from **Gram–Schmidt orthogonalization**.

Applications:
- Least squares
- Numerical stability
- Eigenvalue algorithms


In [ ]:

Q, R = np.linalg.qr(A)
Q, R



## Cholesky Decomposition

If $A$ is **symmetric positive definite**, then

$$
A = LL^T
$$

where $L$ is lower triangular.

Properties:
- Faster than LU
- Numerically stable
- Requires positive definiteness

Common in:
- Optimization
- Covariance matrices


In [2]:

B = np.array([[4., 2.],
              [2., 3.]])

L = np.linalg.cholesky(B)
L


array([[2.        , 0.        ],
       [1.        , 1.41421356]])


## Singular Value Decomposition (SVD)

Every matrix $A \in \mathbb{R}^{m \times n}$ admits

$$
A = U \Sigma V^T
$$

where:
- $U$ and $V$ are orthogonal
- $\Sigma$ is diagonal with nonnegative singular values

Singular values measure:
- Energy
- Rank
- Conditioning

SVD exists **for all matrices**, regardless of shape or rank.


In [3]:

U, s, Vt = np.linalg.svd(A)
U, s, Vt


(array([[-0.26002008,  0.38601219,  0.88508991],
        [-0.85032068,  0.34279446, -0.39930778],
        [-0.45754159, -0.85643829,  0.2391007 ]]),
 array([12.43394263,  4.13842873,  1.12715503]),
 array([[-0.24177687, -0.68863687, -0.68361042],
        [ 0.93177364,  0.03185861, -0.3616392 ],
        [-0.27081697,  0.72440616, -0.63395101]]))


## Geometric Interpretation of SVD

SVD decomposes a linear map into:

1. Rotation ($V^T$)
2. Scaling ($\Sigma$)
3. Rotation ($U$)

This explains:
- Low-rank approximation
- PCA
- Pseudoinverses

SVD is the most powerful decomposition in applied linear algebra.



## Failure Modes and Numerical Notes

- LU without pivoting may fail
- QR is more stable than LU
- Cholesky fails if $A$ is not positive definite
- SVD is stable but computationally expensive

Trade-off:
> Stability vs. computational cost



## Summary

Key takeaways:

- Decompositions simplify matrix problems
- LU: fast solves
- QR: orthogonality and stability
- Cholesky: efficient for SPD matrices
- SVD: universal and robust

Next: **Inner product spaces**, the geometric foundation behind these decompositions.
